In [1]:
import pandas as pd

# Reading data

In [2]:
df=pd.read_csv('covid.csv')

In [3]:
df.head()

fever  bodypain  age  runnynose  diffbreath  prob
0  101.393816         0   32          1           1     1
1  101.827696         0   69          0           0     1
2   98.130859         1   86          0           1     1
3   99.014228         0   24          1           0     1
4  100.001092         1    8          0          -1     0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2135 entries, 0 to 2134
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   fever       2135 non-null   float64
 1   bodypain    2135 non-null   int64  
 2   age         2135 non-null   int64  
 3   runnynose   2135 non-null   int64  
 4   diffbreath  2135 non-null   int64  
 5   prob        2135 non-null   int64  
dtypes: float64(1), int64(5)
memory usage: 100.2 KB


In [5]:
df['diffbreath'].value_counts()

 0    729
-1    714
 1    692
Name: diffbreath, dtype: int64

# train test split


In [6]:
import numpy as np

In [7]:
from sklearn.model_selection import train_test_split
train_set,test_set=train_test_split(df,test_size=0.2,random_state=42)
# this will print length of test set and train set
print("test data is",len(test_set))
print("train data is",len(train_set))

test data is 427
train data is 1708


In [8]:
train_set

fever  bodypain  age  runnynose  diffbreath  prob
192    99.739016         0   33          1           1     1
1307  101.056586         0   33          0          -1     0
482   101.064589         1   92          1           1     1
1054   99.252683         0   98          1          -1     0
1131  101.391988         0   60          1           1     1
...          ...       ...  ...        ...         ...   ...
1638  100.226510         0   87          1          -1     1
1095  100.311670         0   75          0           1     1
1130   98.467102         0    8          1           0     1
1294  100.770369         1   36          1           0     0
860    98.035591         0   29          0           0     1

[1708 rows x 6 columns]

In [9]:
test_set

fever  bodypain  age  runnynose  diffbreath  prob
1429  100.982995         1   84          0           1     0
231   101.848363         1    5          0          -1     0
2019  100.826477         0   49          0           0     1
297   101.033881         0   87          0           0     0
2053   99.533140         1   34          0           0     0
...          ...       ...  ...        ...         ...   ...
1554  101.537635         1    9          1          -1     1
305   101.714610         1   31          1           1     0
1375   99.653663         0   73          0          -1     1
1036   98.832992         0   12          0           1     1
2117  101.072224         0   45          0           0     0

[427 rows x 6 columns]

# for training:seperating features and labels

In [21]:
x_train_feature=train_set.drop(["prob"],axis=1)
y_train_label=train_set["prob"].copy()



In [22]:
# to convert to array
x_train_feature.to_numpy()

array([[ 99.73901646,   0.        ,  33.        ,   1.        ,
          1.        ],
       [101.0565856 ,   0.        ,  33.        ,   0.        ,
         -1.        ],
       [101.0645889 ,   1.        ,  92.        ,   1.        ,
          1.        ],
       ...,
       [ 98.46710242,   0.        ,   8.        ,   1.        ,
          0.        ],
       [100.7703691 ,   1.        ,  36.        ,   1.        ,
          0.        ],
       [ 98.0355907 ,   0.        ,  29.        ,   0.        ,
          0.        ]])

In [26]:
y_train_label.to_numpy()

array([1, 0, 1, ..., 1, 0, 1], dtype=int64)

# for testing:seperating features and labels

In [17]:
x_test_feature=test_set.drop(["prob"],axis=1)
y_test_label=test_set["prob"].copy()


In [18]:
x_test_feature.to_numpy()

array([[100.9829949 ,   1.        ,  84.        ,   0.        ,
          1.        ],
       [101.8483629 ,   1.        ,   5.        ,   0.        ,
         -1.        ],
       [100.8264769 ,   0.        ,  49.        ,   0.        ,
          0.        ],
       ...,
       [ 99.65366282,   0.        ,  73.        ,   0.        ,
         -1.        ],
       [ 98.83299151,   0.        ,  12.        ,   0.        ,
          1.        ],
       [101.0722236 ,   0.        ,  45.        ,   0.        ,
          0.        ]])

In [27]:
y_test_label.to_numpy()

array([0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,

# logistic regression

In [49]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

In [57]:
model=LogisticRegression()
# model=DecisionTreeRegressor()
# model=RandomForestRegressor()

# fit function takes label and features
model.fit(x_train_feature,y_train_label)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [64]:
# using mean squared error
# from sklearn.metrics import mean_squared_error
# covid_predictions=model.predict(x_train_feature)
# lin_mse=mean_squared_error(y_train_label,covid_predictions)
# lin_rmse=np.sqrt(lin_mse)
# lin_rmse

0.6945758397681966

In [65]:
# covid_predictions

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [67]:
# y_train_label.to_numpy()

array([1, 0, 1, ..., 1, 0, 1], dtype=int64)

In [61]:
probability=model.predict_proba([[102,1,0,1,1]])

In [62]:
probability[0][1]

0.5029541621029856